services:
  - type: worker
    name: ebay-inventory-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ebay_inventory_monitor.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_bot_token
      - key: CHAT_ID
        value: your_chat_id
      - key: SELLER_USERNAME
        value: ebay_seller_id
      - key: POLL_INTERVAL
        value: "900"  # 15 minutes in seconds
