# render.yaml
services:
  - type: web
    name: ebay-monitor-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() --threads 4
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}
      - key: CHAT_ID
        value: ${CHAT_ID}
      - key: SELLER_USERNAME
        value: ${SELLER_USERNAME}
      - key: SECRET_KEY
        generateValue: true
    plan: free
