services:
  - type: web
    name: ebay-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ebay_inventory_monitor.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}
      - key: CHAT_ID
        value: ${CHAT_ID}
      - key: SELLER_USERNAME
        value: ${SELLER_USERNAME}
      - key: PORT
        value: 10000
    plan: free
