services:
  - type: worker
    name: ebay-new-listings-monitor
    runtime: python
    buildCommand: pip install feedparser python-telegram-bot
    startCommand: python ebay_monitor.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token
      - key: CHAT_ID
        value: your_telegram_chat_id
      - key: SELLER_USERNAME
        value: ebay_seller_username
