services:
  - type: web
    name: ebay-seller-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python ebay_monitor.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: your_telegram_bot_token
      - key: CHAT_ID
        value: your_telegram_chat_id
      - key: EBAY_APP_ID
        value: your_ebay_app_id
      - key: EBAY_CERT_ID
        value: your_ebay_cert_id
      - key: EBAY_DEV_ID
        value: your_ebay_dev_id
      - key: SELLER_USERNAME
        value: ebay_seller_username_to_monitor
